import '../../domain/maison/entities/maison.dart';
import '../../domain/maison/value_objects/localisation.dart';
import '../../domain/maison/value_objects/statut_maison.dart';
import '../../domain/maison/value_objects/type_maison.dart';

final maisonsMock = [
  Maison.creer(
    id: 'M-001',
    titre: 'Villa Bastos',
    localisation: Localisation(3.8490, 11.5035),
    type: TypeMaison.villa,
    statut: StatutMaison.disponible,
    prix: 185000000,
    ville: 'Yaoundé',
    quartier: 'Bastos',
    description:
        'Grande villa avec jardin, sécurisée, proximité centres internationaux.',
    chambres: 5,
    sallesDeBain: 4,
    etages: 2,
    surfaceHabitableM2: 320,
    surfaceTerrainM2: 800,
    agentId: 'USR-003',
    agentWhatsapp: '237699000001',
    photos: const [],
  ),
  Maison.creer(
    id: 'M-002',
    titre: 'Appartement Akwa',
    localisation: Localisation(4.0520, 9.7018),
    type: TypeMaison.appartement,
    statut: StatutMaison.enNegociation,
    prix: 45000000,
    ville: 'Douala',
    quartier: 'Akwa',
    description: 'Appartement lumineux 4ème étage, vue ville.',
    chambres: 3,
    sallesDeBain: 2,
    etages: 1,
    surfaceHabitableM2: 110,
    agentId: 'USR-002',
    agentWhatsapp: '237699000002',
    photos: const [],
  ),
  Maison.creer(
    id: 'M-003',
    titre: 'Duplex Melen',
    localisation: Localisation(3.8535, 11.5110),
    type: TypeMaison.duplex,
    statut: StatutMaison.disponible,
    prix: 95000000,
    ville: 'Yaoundé',
    quartier: 'Melen',
    description: 'Duplex familial moderne, garage 2 voitures.',
    chambres: 4,
    sallesDeBain: 3,
    etages: 2,
    surfaceHabitableM2: 210,
    agentId: 'USR-003',
    agentWhatsapp: '237699000001',
    photos: const [],
  ),
  Maison.creer(
    id: 'M-004',
    titre: 'Studio Bafoussam',
    localisation: Localisation(5.4795, 10.4205),
    type: TypeMaison.studio,
    statut: StatutMaison.disponible,
    prix: 12000000,
    ville: 'Bafoussam',
    quartier: 'Djeleng',
    description: 'Studio meublé idéal investissement locatif.',
    chambres: 1,
    sallesDeBain: 1,
    etages: 1,
    surfaceHabitableM2: 35,
    agentId: 'USR-002',
    agentWhatsapp: '237699000002',
    photos: const [],
  ),
];
